name: Syntax Check

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Python syntax
      run: |
        python -m py_compile $(find . -name "*.py" -not -path "./venv/*" -not -path "./.venv/*")
        
    - name: Check with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics